using GcwSheetOptimizer.Data;
using GcwSheetOptimizer.Services;
using GcwSheetOptimizer.Components;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using GcwSheetOptimizer.Services.Nesting;

// ---------------------------------------------------------------------------
// Program.cs - the entry point of the app.
// This sets up services (dependency injection), the database connection,
// and the Blazor rendering pipeline, then starts the web server.
// ---------------------------------------------------------------------------

var builder = WebApplication.CreateBuilder(args);

// --- Blazor Server ---------------------------------------------------------
// "Interactive server components" means the UI runs on the server and talks
// to the browser over a SignalR (websocket) connection.
builder.Services.AddRazorComponents()
    .AddInteractiveServerComponents();

// --- Database (EF Core + PostgreSQL) ---------------------------------------
// The connection string comes from configuration. In Docker it is provided
// via the environment variable ConnectionStrings__DefaultConnection
// (see docker-compose.yml). When running locally without Docker it falls
// back to appsettings.json.
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection")
    ?? throw new InvalidOperationException(
        "No connection string found. Set ConnectionStrings__DefaultConnection " +
        "as an environment variable, or add it to appsettings.json.");

// We register a *factory* instead of a plain DbContext. In Blazor Server a
// page can stay open a long time, so the recommended pattern is to create a
// short-lived DbContext for each operation via the factory.
builder.Services.AddDbContextFactory<AppDbContext>(options =>
    options.UseNpgsql(connectionString)
           // The initial migration in this repo was written by hand (not
           // generated by `dotnet ef`), so EF's "pending model changes"
           // check can produce a false alarm. This line turns that check
           // into a no-op. If you add migrations yourself later with
           // `dotnet ef migrations add`, you can safely remove this line.
           .ConfigureWarnings(w => w.Ignore(RelationalEventId.PendingModelChangesWarning)));

// --- Our own services -------------------------------------------------------
builder.Services.AddScoped<CsvImportService>();   // parses uploaded CSV files
builder.Services.AddScoped<NestingService>();     // the guillotine optimizer

var app = builder.Build();

// --- Apply database migrations automatically on startup ---------------------
// This means "docker compose up" is all you need - no manual migration step.
// We retry a few times because even with the compose healthcheck, Postgres
// can occasionally take a moment longer to accept connections.
using (var scope = app.Services.CreateScope())
{
    var factory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<AppDbContext>>();
    var logger = scope.ServiceProvider.GetRequiredService<ILogger<Program>>();

    const int maxAttempts = 10;
    for (var attempt = 1; attempt <= maxAttempts; attempt++)
    {
        try
        {
            using var db = factory.CreateDbContext();
            db.Database.Migrate(); // creates the database schema if needed
            logger.LogInformation("Database migrations applied successfully.");
            break;
        }
        catch (Exception ex) when (attempt < maxAttempts)
        {
            logger.LogWarning(
                "Database not ready yet (attempt {Attempt}/{Max}): {Message}. Retrying in 3s...",
                attempt, maxAttempts, ex.Message);
            Thread.Sleep(3000);
        }
    }
}

// --- HTTP pipeline -----------------------------------------------------------
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Error", createScopeForErrors: true);
}

app.UseStaticFiles();   // serves files from wwwroot (css etc.)
app.UseAntiforgery();

app.MapRazorComponents<App>()
    .AddInteractiveServerRenderMode();

app.Run();
